// Generated by gbahelper.com
// Conversion mode: Tiles (8x8 squares, 256-color palette)

#ifndef IMAGE_TILES_H
#define IMAGE_TILES_H

#include <stdint.h>

#include "gba_types.h"

#define IMAGE_TILES_WIDTH 10
#define IMAGE_TILES_HEIGHT 22

#define IMAGE_TILES_PALETTE_SIZE 67

extern const u8 IMAGE_TILES_DATA [];
extern const u16 IMAGE_TILES_PALETTE [];

#endif
