// Generated by gbahelper.com
// Conversion mode: Tiles (8x8 squares, 256-color palette)

#ifndef IMAGE_RAT_DEFAULT_WALK_H
#define IMAGE_RAT_DEFAULT_WALK_H

#include <stdint.h>

#include "gba_types.h"

#define IMAGE_RAT_DEFAULT_WALK_WIDTH 2
#define IMAGE_RAT_DEFAULT_WALK_HEIGHT 4
#define IMAGE_RAT_DEFAULT_WALK_PALETTE_SIZE 6

extern const u8 IMAGE_RAT_DEFAULT_WALK_DATA [];
extern const u16 IMAGE_RAT_DEFAULT_WALK_PALETTE [];

#endif
