// Generated by gbahelper.com
// Conversion mode: Tiles (8x8 squares, 256-color palette)

#ifndef IMAGE_RAT_DEFAULT_WALK_H
#define IMAGE_RAT_DEFAULT_WALK_H

#include <stdint.h>

#define IMAGE_RAT_DEFAULT_WALK_WIDTH 2
#define IMAGE_RAT_DEFAULT_WALK_HEIGHT 4
#define IMAGE_RAT_DEFAULT_WALK_PALETTE_SIZE 6

extern const uint8_t IMAGE_RAT_DEFAULT_WALK_DATA [];
extern const uint16_t IMAGE_RAT_DEFAULT_WALK_PALETTE [];

#endif
