// Generated by gbahelper.com
// Conversion mode: Tiles (8x8 squares, 256-color palette)

#ifndef IMAGE_TILES_H
#define IMAGE_TILES_H

#include <stdint.h>

#define IMAGE_TILES_WIDTH 80
#define IMAGE_TILES_HEIGHT 64

#define IMAGE_TILES_PALETTE_SIZE 26

extern const uint8_t IMAGE_TILES_DATA [];
extern const uint16_t IMAGE_TILES_PALETTE [];

#endif
