// Generated by gbahelper.com
// Conversion mode: Tiles (8x8 squares, 256-color palette)

#ifndef TILES25_H
#define TILES25_H

#include <stdint.h>

#define TILES25_WIDTH 80
#define TILES25_HEIGHT 64

#define TILES25_PALETTE_SIZE 26

extern const uint8_t TILES25_IMAGE [];
extern const uint16_t TILES25_PALETTE [];

#endif
